In [1]:
import pandas as pd 

df = pd.read_csv('PIT Count Data - 2021 - Sheet1.csv')

df.head()

,CoC Number,CoC Name,Count Types,Overall Homeless,Overall Homeless - Under 18,Overall Homeless - Age 18 to 24,Overall Homeless - Over 24,Overall Homeless - Female,Overall Homeless - Male,Overall Homeless - Transgender,...,Overall Homeless Parenting Youth Age 18-24,Sheltered ES Homeless Parenting Youth Age 18-24,Sheltered TH Homeless Parenting Youth Age 18-24,Sheltered Total Homeless Parenting Youth Age 18-24,Unsheltered Homeless Parenting Youth Age 18-24,Overall Homeless Children of Parenting Youth,Sheltered ES Homeless Children of Parenting Youth,Sheltered TH Homeless Children of Parenting Youth,Sheltered Total Homeless Children of Parenting Youth,Unsheltered Homeless Children of Parenting Youth
0,AK-500,Anchorage CoC,aa,"1,319",156,220,943,414,900,5,...,43,28,15,43,0.0,38,19,19,38,0.0
1,AK-501,Alaska Balance of State CoC,Sheltered-Only Count,630,146,85,399,258,372,0,...,15,7,8,15,0.0,23,10,13,23,0.0
2,AL-500,"Birmingham/Jefferson, St. Clair, Shelby Counti...",Sheltered and Unsheltered Count,875,70,39,766,242,627,6,...,5,3,2,5,0.0,5,3,2,5,0.0
3,AL-501,Mobile City & County/Baldwin County CoC,Sheltered-Only Count,219,78,6,135,96,123,0,...,4,3,1,4,0.0,9,6,3,9,0.0
4,AL-502,Florence/Northwest Alabama CoC,Sheltered and Partial Unsheltered Count,183,0,2,181,85,97,0,...,0,0,0,0,0.0,0,0,0,0,0.0